// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.virginia.shanti.om.bridge.domain;

import edu.virginia.shanti.om.bridge.domain.BridgeDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BridgeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BridgeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BridgeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: BridgeIntegrationTest: @Transactional;
    
    @Autowired
    private BridgeDataOnDemand BridgeIntegrationTest.dod;
    
    @Test
    public void BridgeIntegrationTest.testCountBridges() {
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to initialize correctly", dod.getRandomBridge());
        long count = edu.virginia.shanti.om.bridge.domain.Bridge.countBridges();
        org.junit.Assert.assertTrue("Counter for 'Bridge' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BridgeIntegrationTest.testFindBridge() {
        edu.virginia.shanti.om.bridge.domain.Bridge obj = dod.getRandomBridge();
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.Bridge.findBridge(id);
        org.junit.Assert.assertNotNull("Find method for 'Bridge' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Bridge' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BridgeIntegrationTest.testFindAllBridges() {
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to initialize correctly", dod.getRandomBridge());
        long count = edu.virginia.shanti.om.bridge.domain.Bridge.countBridges();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Bridge', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.virginia.shanti.om.bridge.domain.Bridge> result = edu.virginia.shanti.om.bridge.domain.Bridge.findAllBridges();
        org.junit.Assert.assertNotNull("Find all method for 'Bridge' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Bridge' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BridgeIntegrationTest.testFindBridgeEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to initialize correctly", dod.getRandomBridge());
        long count = edu.virginia.shanti.om.bridge.domain.Bridge.countBridges();
        if (count > 20) count = 20;
        java.util.List<edu.virginia.shanti.om.bridge.domain.Bridge> result = edu.virginia.shanti.om.bridge.domain.Bridge.findBridgeEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Bridge' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Bridge' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BridgeIntegrationTest.testFlush() {
        edu.virginia.shanti.om.bridge.domain.Bridge obj = dod.getRandomBridge();
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.Bridge.findBridge(id);
        org.junit.Assert.assertNotNull("Find method for 'Bridge' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBridge(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Bridge' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BridgeIntegrationTest.testMerge() {
        edu.virginia.shanti.om.bridge.domain.Bridge obj = dod.getRandomBridge();
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.Bridge.findBridge(id);
        boolean modified =  dod.modifyBridge(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.virginia.shanti.om.bridge.domain.Bridge merged = (edu.virginia.shanti.om.bridge.domain.Bridge) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Bridge' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BridgeIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to initialize correctly", dod.getRandomBridge());
        edu.virginia.shanti.om.bridge.domain.Bridge obj = dod.getNewTransientBridge(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Bridge' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Bridge' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BridgeIntegrationTest.testRemove() {
        edu.virginia.shanti.om.bridge.domain.Bridge obj = dod.getRandomBridge();
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Bridge' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.Bridge.findBridge(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Bridge' with identifier '" + id + "'", edu.virginia.shanti.om.bridge.domain.Bridge.findBridge(id));
    }
    
}
