// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.virginia.shanti.om.bridge.domain;

import edu.virginia.shanti.om.bridge.domain.PermissionMapDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PermissionMapIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PermissionMapIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PermissionMapIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PermissionMapIntegrationTest: @Transactional;
    
    @Autowired
    private PermissionMapDataOnDemand PermissionMapIntegrationTest.dod;
    
    @Test
    public void PermissionMapIntegrationTest.testCountPermissionMaps() {
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to initialize correctly", dod.getRandomPermissionMap());
        long count = edu.virginia.shanti.om.bridge.domain.PermissionMap.countPermissionMaps();
        org.junit.Assert.assertTrue("Counter for 'PermissionMap' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PermissionMapIntegrationTest.testFindPermissionMap() {
        edu.virginia.shanti.om.bridge.domain.PermissionMap obj = dod.getRandomPermissionMap();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.PermissionMap.findPermissionMap(id);
        org.junit.Assert.assertNotNull("Find method for 'PermissionMap' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'PermissionMap' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PermissionMapIntegrationTest.testFindAllPermissionMaps() {
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to initialize correctly", dod.getRandomPermissionMap());
        long count = edu.virginia.shanti.om.bridge.domain.PermissionMap.countPermissionMaps();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'PermissionMap', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.virginia.shanti.om.bridge.domain.PermissionMap> result = edu.virginia.shanti.om.bridge.domain.PermissionMap.findAllPermissionMaps();
        org.junit.Assert.assertNotNull("Find all method for 'PermissionMap' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'PermissionMap' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PermissionMapIntegrationTest.testFindPermissionMapEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to initialize correctly", dod.getRandomPermissionMap());
        long count = edu.virginia.shanti.om.bridge.domain.PermissionMap.countPermissionMaps();
        if (count > 20) count = 20;
        java.util.List<edu.virginia.shanti.om.bridge.domain.PermissionMap> result = edu.virginia.shanti.om.bridge.domain.PermissionMap.findPermissionMapEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'PermissionMap' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'PermissionMap' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PermissionMapIntegrationTest.testFlush() {
        edu.virginia.shanti.om.bridge.domain.PermissionMap obj = dod.getRandomPermissionMap();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.PermissionMap.findPermissionMap(id);
        org.junit.Assert.assertNotNull("Find method for 'PermissionMap' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPermissionMap(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PermissionMap' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PermissionMapIntegrationTest.testMerge() {
        edu.virginia.shanti.om.bridge.domain.PermissionMap obj = dod.getRandomPermissionMap();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.PermissionMap.findPermissionMap(id);
        boolean modified =  dod.modifyPermissionMap(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.virginia.shanti.om.bridge.domain.PermissionMap merged = (edu.virginia.shanti.om.bridge.domain.PermissionMap) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'PermissionMap' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PermissionMapIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to initialize correctly", dod.getRandomPermissionMap());
        edu.virginia.shanti.om.bridge.domain.PermissionMap obj = dod.getNewTransientPermissionMap(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'PermissionMap' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'PermissionMap' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PermissionMapIntegrationTest.testRemove() {
        edu.virginia.shanti.om.bridge.domain.PermissionMap obj = dod.getRandomPermissionMap();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionMap' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.PermissionMap.findPermissionMap(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'PermissionMap' with identifier '" + id + "'", edu.virginia.shanti.om.bridge.domain.PermissionMap.findPermissionMap(id));
    }
    
}
