// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.virginia.shanti.om.bridge.domain;

import edu.virginia.shanti.om.bridge.domain.PermissionSet;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect PermissionSetDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PermissionSetDataOnDemand: @Component;
    
    private Random PermissionSetDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<PermissionSet> PermissionSetDataOnDemand.data;
    
    public PermissionSet PermissionSetDataOnDemand.getNewTransientPermissionSet(int index) {
        edu.virginia.shanti.om.bridge.domain.PermissionSet obj = new edu.virginia.shanti.om.bridge.domain.PermissionSet();
        setGroupName(obj, index);
        setLocalGroupType(obj, index);
        return obj;
    }
    
    private void PermissionSetDataOnDemand.setGroupName(PermissionSet obj, int index) {
        java.lang.String groupName = "groupName_" + index;
        obj.setGroupName(groupName);
    }
    
    private void PermissionSetDataOnDemand.setLocalGroupType(PermissionSet obj, int index) {
        edu.virginia.shanti.om.bridge.domain.LocalGroupType localGroupType = edu.virginia.shanti.om.bridge.domain.LocalGroupType.class.getEnumConstants()[0];
        obj.setLocalGroupType(localGroupType);
    }
    
    public PermissionSet PermissionSetDataOnDemand.getSpecificPermissionSet(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        PermissionSet obj = data.get(index);
        return PermissionSet.findPermissionSet(obj.getId());
    }
    
    public PermissionSet PermissionSetDataOnDemand.getRandomPermissionSet() {
        init();
        PermissionSet obj = data.get(rnd.nextInt(data.size()));
        return PermissionSet.findPermissionSet(obj.getId());
    }
    
    public boolean PermissionSetDataOnDemand.modifyPermissionSet(PermissionSet obj) {
        return false;
    }
    
    public void PermissionSetDataOnDemand.init() {
        data = edu.virginia.shanti.om.bridge.domain.PermissionSet.findPermissionSetEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'PermissionSet' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<edu.virginia.shanti.om.bridge.domain.PermissionSet>();
        for (int i = 0; i < 10; i++) {
            edu.virginia.shanti.om.bridge.domain.PermissionSet obj = getNewTransientPermissionSet(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
