// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.virginia.shanti.om.bridge.domain;

import edu.virginia.shanti.om.bridge.domain.PermissionSetDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PermissionSetIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PermissionSetIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PermissionSetIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PermissionSetIntegrationTest: @Transactional;
    
    @Autowired
    private PermissionSetDataOnDemand PermissionSetIntegrationTest.dod;
    
    @Test
    public void PermissionSetIntegrationTest.testCountPermissionSets() {
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to initialize correctly", dod.getRandomPermissionSet());
        long count = edu.virginia.shanti.om.bridge.domain.PermissionSet.countPermissionSets();
        org.junit.Assert.assertTrue("Counter for 'PermissionSet' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PermissionSetIntegrationTest.testFindPermissionSet() {
        edu.virginia.shanti.om.bridge.domain.PermissionSet obj = dod.getRandomPermissionSet();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.PermissionSet.findPermissionSet(id);
        org.junit.Assert.assertNotNull("Find method for 'PermissionSet' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'PermissionSet' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PermissionSetIntegrationTest.testFindAllPermissionSets() {
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to initialize correctly", dod.getRandomPermissionSet());
        long count = edu.virginia.shanti.om.bridge.domain.PermissionSet.countPermissionSets();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'PermissionSet', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.virginia.shanti.om.bridge.domain.PermissionSet> result = edu.virginia.shanti.om.bridge.domain.PermissionSet.findAllPermissionSets();
        org.junit.Assert.assertNotNull("Find all method for 'PermissionSet' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'PermissionSet' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PermissionSetIntegrationTest.testFindPermissionSetEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to initialize correctly", dod.getRandomPermissionSet());
        long count = edu.virginia.shanti.om.bridge.domain.PermissionSet.countPermissionSets();
        if (count > 20) count = 20;
        java.util.List<edu.virginia.shanti.om.bridge.domain.PermissionSet> result = edu.virginia.shanti.om.bridge.domain.PermissionSet.findPermissionSetEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'PermissionSet' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'PermissionSet' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PermissionSetIntegrationTest.testFlush() {
        edu.virginia.shanti.om.bridge.domain.PermissionSet obj = dod.getRandomPermissionSet();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.PermissionSet.findPermissionSet(id);
        org.junit.Assert.assertNotNull("Find method for 'PermissionSet' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPermissionSet(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PermissionSet' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PermissionSetIntegrationTest.testMerge() {
        edu.virginia.shanti.om.bridge.domain.PermissionSet obj = dod.getRandomPermissionSet();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.PermissionSet.findPermissionSet(id);
        boolean modified =  dod.modifyPermissionSet(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.virginia.shanti.om.bridge.domain.PermissionSet merged = (edu.virginia.shanti.om.bridge.domain.PermissionSet) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'PermissionSet' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PermissionSetIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to initialize correctly", dod.getRandomPermissionSet());
        edu.virginia.shanti.om.bridge.domain.PermissionSet obj = dod.getNewTransientPermissionSet(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'PermissionSet' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'PermissionSet' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PermissionSetIntegrationTest.testRemove() {
        edu.virginia.shanti.om.bridge.domain.PermissionSet obj = dod.getRandomPermissionSet();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PermissionSet' failed to provide an identifier", id);
        obj = edu.virginia.shanti.om.bridge.domain.PermissionSet.findPermissionSet(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'PermissionSet' with identifier '" + id + "'", edu.virginia.shanti.om.bridge.domain.PermissionSet.findPermissionSet(id));
    }
    
}
