// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.virginia.shanti.om.bridge.domain;

import edu.virginia.shanti.om.bridge.domain.PermissionMap;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect PermissionMapDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PermissionMapDataOnDemand: @Component;
    
    private Random PermissionMapDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<PermissionMap> PermissionMapDataOnDemand.data;
    
    public PermissionMap PermissionMapDataOnDemand.getNewTransientPermissionMap(int index) {
        edu.virginia.shanti.om.bridge.domain.PermissionMap obj = new edu.virginia.shanti.om.bridge.domain.PermissionMap();
        obj.setName("name_" + index);
        obj.setLocalContextMask("localContextMask_" + index);
        obj.setService("service_" + index);
        obj.setLocalContextType(null);
        return obj;
    }
    
    public PermissionMap PermissionMapDataOnDemand.getSpecificPermissionMap(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        PermissionMap obj = data.get(index);
        return PermissionMap.findPermissionMap(obj.getId());
    }
    
    public PermissionMap PermissionMapDataOnDemand.getRandomPermissionMap() {
        init();
        PermissionMap obj = data.get(rnd.nextInt(data.size()));
        return PermissionMap.findPermissionMap(obj.getId());
    }
    
    public boolean PermissionMapDataOnDemand.modifyPermissionMap(PermissionMap obj) {
        return false;
    }
    
    public void PermissionMapDataOnDemand.init() {
        data = edu.virginia.shanti.om.bridge.domain.PermissionMap.findPermissionMapEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'PermissionMap' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<edu.virginia.shanti.om.bridge.domain.PermissionMap>();
        for (int i = 0; i < 10; i++) {
            edu.virginia.shanti.om.bridge.domain.PermissionMap obj = getNewTransientPermissionMap(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
