// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.virginia.shanti.om.bridge.service;

import org.springframework.security.core.Authentication;

privileged aspect CurrentUserImpl_Roo_JavaBean {
    
    public void CurrentUserImpl.setAuthentication(Authentication authentication) {
        this.authentication = authentication;
    }
    
}
