// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.virginia.shanti.om.bridge.service;

import java.lang.String;

privileged aspect CurrentUserImpl_Roo_JavaBean {
    
    public String CurrentUserImpl.getUser() {
        return this.user;
    }
    
    public void CurrentUserImpl.setUser(String user) {
        this.user = user;
    }
    
}
