// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.virginia.shanti.om.bridge.form;

import java.io.Serializable;

privileged aspect RemoteContextChoice_Roo_Serializable {
    
    declare parents: RemoteContextChoice implements Serializable;
    
}
