// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.virginia.shanti.om.bridge.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Bridge_Roo_Configurable {
    
    declare @type: Bridge: @Configurable;
    
}
